version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - requirements: requirements.txt

# sphinx:
#   configuration: docs/conf.py   # 不用，mkdocs可无视

mkdocs:
  configuration: mkdocs.yml
